[package]
name = "code-clean"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"
authors = ["Elichai Turkel <elichai.turkel@gmail.com>"]
repository = "https://github.com/elichai/code-clean"
readme = "README.md"
